name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CH_SERVER_VERSION: 21.3.17.2

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [gcc-7, clang-6]
        include:
        - build: gcc-7
          os: ubuntu-latest
          INSTALL: gcc-7 g++-7
          C_COMPILER: gcc-7
          CXX_COMPILER: g++-7

        - build: clang-6
          os: ubuntu-latest
          INSTALL: clang-6.0
          C_COMPILER: clang-6
          CXX_COMPILER: clang++-6

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y ${{ matrix.INSTALL }}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        export C=`which ${{ matrix.C_COMPILER }}`
        export CXX=`which ${{ matrix.CXX_COMPILER }}`
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON


    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Start ClickHouse server
      run: |
        sudo apt-get install apt-transport-https ca-certificates dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
        echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y \
            clickhouse-server=${{env.CH_SERVER_VERSION}} \
            clickhouse-client=${{env.CH_SERVER_VERSION}} \
            clickhouse-common-static=${{env.CH_SERVER_VERSION}}
        sudo service clickhouse-server start

    - name: Test
      working-directory: ${{github.workspace}}/build/ut
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      run: ./clickhouse-cpp-ut "${{env.GTEST_FILTER}}"

